// import type { Film } from "../domain/Film";
// import type { FilmRepository } from "../domain/FilmRepository";

// export default class LocalFilmRepository implements FilmRepository {
//   private films: Film[] = [
//     {
//       id: "1",
//       title: "Titanic",
//       releaseDate: "1997",
//       director: "James Cameron",
//       synopsis: "Una aristócrata de diecisiete años se enamora de un amable pero pobre artista a bordo del lujoso y desafortunado R.M.S. Titanic.",
//       ratingAverage: 8.0,
//       type: "MOVIE",
//       category: "Romance",
//       image: "/000_titanic.jpg",
//     },
//     {
//       id: "2",
//       title: "Back to the Future",
//       releaseDate: "1985",
//       director: "Robert Zemeckis",
//       synopsis: "Marty McFly viaja al pasado en un DeLorean.",
//       ratingAverage: 8.5,
//       type: "MOVIE",
//       category: "Sci-Fi",
//       image: "/001_BackToFuture.jpg",
//     },
//     {
//       id: "3",
//       title: "Lost",
//       releaseDate: "2004-2010",
//       director: "J.J Abrams",
//       synopsis: "Los supervivientes de un accidente aéreo se ven obligados a trabajar juntos para sobrevivir en una isla tropical aparentemente desierta.",
//       ratingAverage: 8.3,
//       type: "SERIE",
//       category: "Drama",
//       image: "/002_Lost.jpg",
//     },
//     {
//       id: "4",
//       title: "The Black Tower",
//       releaseDate: "1987-01-01",
//       director: "John Smith",
//       synopsis: "Una historia inquietante y oscura.",
//       ratingAverage: 2.4,
//       type: "MOVIE",
//       category: "Thriller",
//       image: "/003_TheBlackTower.jpg",
//     },
//     {
//       id: "5",
//       title: "Inception",
//       releaseDate: "2010-07-16",
//       director: "Christopher Nolan",
//       synopsis: "Un ladrón entra en los sueños de sus víctimas.",
//       ratingAverage: 4.7,
//       type: "MOVIE",
//       category: "Sci-Fi",
//       image: "/004_Inception.jpg",
//     },
//     {
//       id: "6",
//       title: "The Dark Knight",
//       releaseDate: "2008-07-18",
//       director: "Christopher Nolan",
//       synopsis: "Batman se enfrenta al Joker.",
//       ratingAverage: 4.8,
//       type: "MOVIE",
//       category: "Action",
//       image: "/005_TheDarkKnight.jpg",
//     },
//     {
//       id: "7",
//       title: "Stranger Things",
//       releaseDate: "2016-2026",
//       director: "Duffer Brothers",
//       synopsis: "Sucesos extraños en un pequeño pueblo.",
//       ratingAverage: 4.3,
//       type: "SERIE",
//       category: "Sci-Fi",
//       image: "/006_StrangerThings.jpg",
//     },
//     {
//       id: "8",
//       title: "Interstellar",
//       releaseDate: "2014-11-07",
//       director: "Christopher Nolan",
//       synopsis: "Una misión espacial para salvar a la humanidad.",
//       ratingAverage: 4.6,
//       type: "MOVIE",
//       category: "Sci-Fi",
//       image: "/007_Interstellar.jpg",
//     },
//     {
//       id: "9",
//       title: "Dark",
//       releaseDate: "2017-2020",
//       director: "Baran bo Odar",
//       synopsis: "Una misión espacial para salvar a la humanidad.",
//       ratingAverage: 8.7,
//       type: "MOVIE",
//       category: "Drama",
//       image: "/008_Dark.jpg",
//     },
//     {
//       id: "10",
//       title: "Jo, que noche",
//       releaseDate: "1985",
//       director: "Martin Scorsese",
//       synopsis: "Una sátira de humor negro de Martin Scorsese sobre las aventuras nocturnas de un hombre en el inframundo de Manhattan.",
//       ratingAverage: 8.9,
//       type: "MOVIE",
//       category: "Comedy",
//       image: "/009_AfterHours.jpg",
//     },
//     {
//       id: "11",
//       title: "Kill Bill: The Whole Bloody Affair",
//       releaseDate: "2006",
//       director: "Quentin Tarantino",
//       synopsis: "Kill Bill: The Whole Bloody Affair es una película estadounidense de artes marciales de 2004 escrita y dirigida por Quentin Tarantino. Combina las películas Kill Bill: Volumen 1 y Kill Bill: Volumen 2, que fueron concebidas y producidas como una sola película, pero divididas en dos.",
//       ratingAverage: 8.2,
//       type: "MOVIE",
//       category: "Action",
//       image: "/010_KillBill.jpg",
//     },
//     {
//       id: "12",
//       title: "The last of us",
//       releaseDate: "20023-2025",
//       director: "Neil Druckman",
//       synopsis: "Joel y Ellie, una pareja conectada a través de la dureza del mundo en el que viven, se ven obligados a soportar circunstancias brutales y asesinos despiadados en un viaje por la América",
//       ratingAverage: 8.5,
//       type: "SERIE",
//       category: "Action",
//       image: "/011_TheLastOfUs.jpg",
//     },
//     {
//       id: "13",
//       title: "Shutter Island",
//       releaseDate: "2010",
//       director: "Martin Scorsese",
//       synopsis: "En 1954, los agentes federales Edward Teddy Daniels (Leonardo DiCaprio) y su recientemente asignado compañero Chuck Aule (Mark Ruffalo), van al hospital de Ashecliffe para personas dementes en Shutter Island, isla situada en el puerto de Boston para investigar la desaparición de Rachel Solando",
//       ratingAverage: 8.2,
//       type: "MOVIE",
//       category: "Thriller",
//       image: "/012_ShutterIsland.jpg",
//     },
//     {
//       id: "14",
//       title: "Monsters, Inc",
//       releaseDate: "2001",
//       director: "Pete Docter, Lee Unkrich, David Silverman",
//       synopsis: "En un mundo habitado por monstruos, la ciudad de Monstruópolis se abastece de la energía obtenida a partir de los gritos de niños humanos. Sin embargo, los monstruos creen que los niños son tóxicos y peligrosos, por lo que se aseguran de que ninguno de ellos entre en su mundo. Sulley, el mejor asustador de la empresa Monsters, Inc., y su compañero Mike Wazowski, se ven envueltos en un gran problema cuando una niña humana llamada Boo entra accidentalmente en Monstruópolis.",
//       ratingAverage: 8.1,
//       type: "MOVIE",
//       category: "Thriller",
//       image: "/013_MonstersInc.jpg",
//     },
//     {
//       id: "15",
//       title: "Padre no hay más que uno 5",
//       releaseDate: "2025",
//       director: "Santiago Segura",
//       synopsis: "Padre no hay más que uno 5: nido repleto es una película de comedia española de la franquicia cinematográfica Padre no hay más que uno dirigida por Santiago Segura.",
//       ratingAverage: 3.6,
//       type: "MOVIE",
//       category: "Comedy",
//       image: "/014_PNHMQ5.jpg",
//     },
//     {
//       id: "16",
//       title: "El planeta del tesoro",
//       releaseDate: "2002",
//       director: "John Musker, Ron Clements",
//       synopsis: "En el planeta Montressor, el joven Jim Hawkins está encantado con las historias del pirata espacial Capitán Flint y su habilidad para atacar repentinamente y desaparecer sin dejar rastro, ocultando su botín en el legendario «Planeta del Tesoro».",
//       ratingAverage: 9.2,
//       type: "MOVIE",
//       category: "Action",
//       image: "/015_ElPlanetaDelTesoro.jpg",
//     },
//   ];

//   async getAll(): Promise<Film[]> {
//     return this.films;
//   }

//   async getById(id: string): Promise<Film | null> {
//     const film = this.films.find((film) => film.id === id);
//     return film || null;
//   }
// }